### ISSUE TITLE
Criação de um Wizard para configuração de um novo plano de medição na MedCEP.

### ISSUE THREAD

**Issue by henribarres** [nemo-ufes/MedCEP#1]
- Remover o menu anterior que mantem os ultimos modulos abertos do sistema.
- Criar um novo menu com um link para uma pagina de tutorial sobre o sistema.
- Criar um outro menu com um link para a pagina inicial do sistema.

**Comment by vinnysoft** [comment]
Na verdade, ao invés da criação do Tutotial, foi sugerido a criação de um Passo a Passo (wizard) para configurar a MedCEP, sugerindo a criação de projetos, equipe, objetivos, etc.

**Comment by vinnysoft** [comment]
Wizard criado.
