### ISSUE TITLE
Completar o menu esquerdo de acordo com os menus da MedCEP da VM

### ISSUE THREAD

**Issue by vinnysoft** [nemo-ufes/MedCEP#2]
Verificar corretamente a árvore de menus da MedCEP da VM (com Liferay) e atualizar o menu lateral esquerdo da nova MedCEP.

**Comment by henribarres** [comment]
Menu lateral atualizado.
Necessario estudar a biblioteca JSTREE para realizar adaptações de interface e layout, melhorando a interação com o usuário.

**Comment by vinnysoft** [comment]
Com a adição de novas classes vindas do projeto Mestrado-Novo, é necessário verificar se o menu ainda está atualizado.

**Comment by vinnysoft** [comment]
Fiz a alteração para a árvore iniciar fechada. Sugestões de melhorias são:
- Alterar os ícones das folhas de acordo com o menu. Ex: Recurso Humano, colocar o ícone de pessoa.
- Deixar aberto a folha que representa a página atual.

**Comment by vinnysoft** [comment]
Implementada a funcionalidade de deixar aberto a folha que representa a página atual.

**Comment by vinnysoft** [comment]
Faltam vários menus, após a adição de novas classes modelo. Quando adicionar os novos itens na árvore, aproveitar e colocar em ordem alfabética.

**Comment by vinnysoft** [comment]
Menus criados.
